/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindMoversRouteImport } from './routes/find-movers'
import { Route as ForMovingCompaniesRouteImport } from './routes/for-moving-companies'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyMoveRouteImport } from './routes/my-move'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMoversRoute = FindMoversRouteImport.update({
  id: '/find-movers',
  path: '/find-movers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForMovingCompaniesRoute = ForMovingCompaniesRouteImport.update({
  id: '/for-moving-companies',
  path: '/for-moving-companies',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMoveRoute = MyMoveRouteImport.update({
  id: '/my-move',
  path: '/my-move',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-movers': typeof FindMoversRoute
  '/for-moving-companies': typeof ForMovingCompaniesRoute
  '/messages': typeof MessagesRoute
  '/my-move': typeof MyMoveRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/saved': typeof SavedRoute
  '/providers/$slug': typeof ProvidersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-movers': typeof FindMoversRoute
  '/for-moving-companies': typeof ForMovingCompaniesRoute
  '/messages': typeof MessagesRoute
  '/my-move': typeof MyMoveRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/saved': typeof SavedRoute
  '/providers/$slug': typeof ProvidersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-movers': typeof FindMoversRoute
  '/for-moving-companies': typeof ForMovingCompaniesRoute
  '/messages': typeof MessagesRoute
  '/my-move': typeof MyMoveRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/saved': typeof SavedRoute
  '/providers/$slug': typeof ProvidersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-movers'
    | '/for-moving-companies'
    | '/messages'
    | '/my-move'
    | '/profile'
    | '/provider'
    | '/saved'
    | '/providers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-movers'
    | '/for-moving-companies'
    | '/messages'
    | '/my-move'
    | '/profile'
    | '/provider'
    | '/saved'
    | '/providers/$slug'
  id:
    | '__root__'
    | '/'
    | '/find-movers'
    | '/for-moving-companies'
    | '/messages'
    | '/my-move'
    | '/profile'
    | '/provider'
    | '/saved'
    | '/providers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindMoversRoute: typeof FindMoversRoute
  ForMovingCompaniesRoute: typeof ForMovingCompaniesRoute
  MessagesRoute: typeof MessagesRoute
  MyMoveRoute: typeof MyMoveRoute
  ProfileRoute: typeof ProfileRoute
  ProviderRoute: typeof ProviderRoute
  SavedRoute: typeof SavedRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-movers': {
      id: '/find-movers'
      path: '/find-movers'
      fullPath: '/find-movers'
      preLoaderRoute: typeof FindMoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-moving-companies': {
      id: '/for-moving-companies'
      path: '/for-moving-companies'
      fullPath: '/for-moving-companies'
      preLoaderRoute: typeof ForMovingCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-move': {
      id: '/my-move'
      path: '/my-move'
      fullPath: '/my-move'
      preLoaderRoute: typeof MyMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindMoversRoute: FindMoversRoute,
  ForMovingCompaniesRoute: ForMovingCompaniesRoute,
  MessagesRoute: MessagesRoute,
  MyMoveRoute: MyMoveRoute,
  ProfileRoute: ProfileRoute,
  ProviderRoute: ProviderRoute,
  SavedRoute: SavedRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
